name: TASK-6-CI

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./5-End-to-End-Testing/frontend

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.x'

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./5-End-to-End-Testing/frontend
        install-command: npm ci
        start: npm start
